### ISSUE TITLE
How can I control the speed of the swerve modules?

### ISSUE THREAD

**Issue by webs98** [dirtbikerxz/BaseTalonFXSwerve#10]
I was wondering how I could limit the speed of the drive motors for testing.  Is there a preexisting line of code that can alter the speed or do we need to add a new line?  If we need to add a line what would the syntax be?

**Comment by davidmuchow** [comment]
https://github.com/Team364/BaseFalconSwerve/blob/main/src/main/java/frc/robot/Constants.java#L83
This line in constants, in meters per second.

**Comment by RedBread7576** [comment]
> https://github.com/Team364/BaseFalconSwerve/blob/main/src/main/java/frc/robot/Constants.java#L83
> 
> This line in constants, in meters per second.


We tried this today, in order to test if we could make the battery last longer if we reduced the maxspeed, however; reducing the maxspeed did absolutely nothing. We even set it to 0.1 in the end, and literally nothing changed. Any ideas? We have the code from 3512 but it's still using the 364 template, so any help would be appreciated

**Comment by dirtbikerxz** [comment]
Reducing max speed there will only affect closed loop max speed. By default, teleop driving is open loop, which simply takes the stick input of 0 -> 1 (0 - 100%). There are multiple ways to limit speed in open loop driving, the easiest way would probably be to clamp joystick input in TeleopSwerve.java.

**Comment by RedBread7576** [comment]
> Reducing max speed there will only affect closed loop max speed. By default, teleop driving is open loop, which simply takes the stick input of 0 -> 1 (0 - 100%). There are multiple ways to limit speed in open loop driving, the easiest way would probably be to clamp joystick input in TeleopSwerve.java.

Hm, but then; if maxspeed doesn't actually have any impact on the speed in teleop mode, and we already have a different constant set for autonomous mode, what's the point of declaring a maxspeed?
