### ISSUE TITLE
When we run auton and set to travel 3 Meters, our robot only moves 2.5 meters. We are using  MK4i_L1 modules and using COTSFalconSwerveConstants to set the module values.

### ISSUE THREAD

**Issue by bburrows76** [dirtbikerxz/BaseTalonFXSwerve#13]

**Comment by mjbergman92** [comment]
I would HIGHLY recommend checking that your tread is not worn. This will change the diameter, hence the distance you cover.

You can measure them, but a more sure-fire way imo, would be to use the pose estimate position after moving the robot a known distance. the equation for your actual diameter of your wheel is:
`actual_diameter = actual_distance/estimate_distance * assumed_diameter`

Try it out and let me know if that fixes it.
