### ISSUE TITLE
Swerve module optimization not working correctly

### ISSUE THREAD

**Issue by haydenheroux** [dirtbikerxz/BaseTalonFXSwerve#14]
During testing of our swerve modules, I noticed that a swerve module would sometimes do multiple rotations in the "wrong" direction rather than a short rotation in the "correct" direction. After debugging, the values returned from the CTREModuleState.placeInAppropriate0To360Scope function are sometimes outside of the -360 to +360 range (or -180 to +180? Not sure of the intended return range). This may be caused by the `scopeReference` parameter being somehow set to a value outside of the -360 to +360 range. This is causing the behavior described above. Is this a known issue and is there a known fix?

**Comment by Git-Nivrak** [comment]
We've also encountered this issue while using different code than the one in this repository. It appears to happen only on mk4i while working fine on mk4 swerve.

**Comment by Git-Nivrak** [comment]
![image](https://user-images.githubusercontent.com/59925169/217908119-e431b15b-574e-4ed1-b4c5-ae42a6c32b7d.png)
This might be the issue, It got fixed but only for PRO...

**Comment by gsesny** [comment]
following

**Comment by bhall-ctre** [comment]
> This might be the issue, It got fixed but only for PRO...

To clarify, this was only an issue in Pro firmware. We haven't made many changes to v5 firmware since last season, so that bug is not present there. That bug is also unrelated to this issue, as its behavior was that the motor would spin to infinity instead of approaching the target if motor invert was true.

**Comment by Git-Nivrak** [comment]
> bhall

Well yesterday is started spinning infinitely too with non pro firmware
