### ISSUE TITLE
Sensor Reading Problems

### ISSUE THREAD

**Issue by t3team-laptop** [dirtbikerxz/BaseTalonFXSwerve#32]
We are preparing for 2024 swerve and we imported this project and made the necessary changes (team number, motor IDs, etc). we keep getting errors when trying to get the CANCoder positions

CTR: CAN frame not received/too-stale.
   from: Talon FX 3 (cani) GetSelectedSensorPosition
     at: Stack Trace not received for performance reasons.

we keep getting zero for our position readouts even when purposefully moving the robot.

we aren't sure if this is a problem with the code for 2024 or not, but we wanted to let yall know in case it is an issue with changing WPIlib versions

**Comment by dirtbikerxz** [comment]
Are you still having this issue? From our own testing with 2024 wpilib we haven't run into this, and I haven't been made aware of anyone else who has either.

**Comment by tomball-robotics** [comment]
it fixed itself after the official 2024 game tools and stuff were out so dw

*T3 Robotics Team 7312 *
*Tomball, TX*

**Comment by dirtbikerxz** [comment]
👍
