### ISSUE TITLE
Is there a base code plan for 2024 and Phoenix6?

### ISSUE THREAD

**Issue by BirdyBirdoBird** [dirtbikerxz/BaseTalonFXSwerve#34]
My team and I were wondering if there's a base code coming to 2024. I've seen the branch but we want to be ready before the season starts.

**Comment by dirtbikerxz** [comment]
Yes, I'll get it pushed out in the next week or so!

**Comment by github3658** [comment]
Any update on the code push for phoenix 6 and thank you for what you do for the FRC Community?

**Comment by dirtbikerxz** [comment]
It's been written already, planning on putting its through its paces and testing it on our bots either this weekend or early next week to make sure everything's working before pushing it to main!

**Comment by github3658** [comment]
@dirtbikerxz You are the PERSON!!! Thank you for such a quick response! Bonus note I host a FRC Robotics podcast and I would like to do an episode on this project if you are willing to come on board the RoboZone Podcast! Just send me an email at robozonepodcast@gmail.com and we can get you on board the podcast SOON! Link for reference: https://www.youtube.com/c/RoboZoneTV

**Comment by dirtbikerxz** [comment]
@github3658 Sorry, been a busy week. Just pushed the changes. See the note at the top of the readme. 

Updated everything to 2024 (beta) Phoenix 6 and WPILib, and was able to ensure everything is working on our MK4i's. 

We don't have the other modules to test, however the configs should all be correct but the angle motor PID's will need to be retuned with the change to phoenix6.
