### ISSUE TITLE
error report: "internal issue with print and error tags."

### ISSUE THREAD

**Issue by vitojan** [dirtbikerxz/BaseTalonFXSwerve#39]
**Description of the Issue**
When the robot is enabled, it only moves for approximately 5 to 20 and then stops. Additionally, an error is reported: "internal issue with print and error tags." on the FRC Driver Station.

**Steps to Reproduce**
After uploading the code, press [Enable].

 - Code Link: [https://drive.google.com/file/d/1FnMK5D-NExMq3QSRd2-rVercRD_zdk9D/view?usp=sharing](https://drive.google.com/file/d/1FnMK5D-NExMq3QSRd2-rVercRD_zdk9D/view?usp=sharing)

![image](https://github.com/wpilibsuite/allwpilib/assets/56464847/0f834ca8-2f0a-4960-b5cf-1a6e18e5f1d0)

**Desktop Environment:**
 - OS: Windows 10
 - Project Information:
    ```groovy
    plugins {
        id "java"
        id "edu.wpi.first.GradleRIO" version "2024.1.1"
    }

    java {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
    ```

    ```json
    {
        "fileName": "Phoenix6.json",
        "name": "CTRE-Phoenix (v6)",
        "version": "24.0.0-beta-7",
        "frcYear": 2024,
        "uuid": "e995de00-2c64-4df5-8831-c1441420ff19",
        "mavenUrls": [
            "https://maven.ctr-electronics.com/release/"
        ],
        "jsonUrl": "https://maven.ctr-electronics.com/release/com/ctre/phoenix6/latest/Phoenix6-frc2024-beta-latest.json"...
    }

    {
      "fileName": "WPILibNewCommands.json",
      "name": "WPILib-New-Commands",
      "version": "1.0.0",
      "uuid": "111e20f7-815e-48f8-9dd6-e675ce75b266",
      "frcYear": "2024",
      "mavenUrls": [],
      "jsonUrl": ""...
    }
    ```

**Comment by dirtbikerxz** [comment]
This is a bug with the driverstation, not a code issue and can be ignored. From what I'm told it will be fixed in a future update.
